/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKalamangFeeStorage, IKalamangFeeStorageInterface } from "../../interfaces/IKalamangFeeStorage.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getFee",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IKalamangFeeStorage__factory {
    static readonly abi = _abi;
    static createInterface(): IKalamangFeeStorageInterface {
      return new Interface(_abi) as IKalamangFeeStorageInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKalamangFeeStorage {
      return new Contract(address, _abi, runner) as unknown as IKalamangFeeStorage;
    }
  }
  