/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKalamangStorage, IKalamangStorageInterface } from "../../interfaces/IKalamangStorage.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_kalamangId",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "_creator",
        "type": "address"
      }
    ],
    "name": "abortKalamang",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_kalamangId",
        "type": "string"
      },
      {
        "internalType": "address[]",
        "name": "_whitelist",
        "type": "address[]"
      },
      {
        "internalType": "address",
        "name": "_creator",
        "type": "address"
      }
    ],
    "name": "addWhitelist",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_kalamangId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "_claimTokens",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "_recipient",
        "type": "address"
      }
    ],
    "name": "claimToken",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "kalamangId",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "creator",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "tokenAddress",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "totalTokens",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "maxRecipients",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isRandom",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "minRandom",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "maxRandom",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "acceptedKYCLevel",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isClaimable",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "isRequireWhitelist",
            "type": "bool"
          },
          {
            "internalType": "address[]",
            "name": "whitelist",
            "type": "address[]"
          },
          {
            "internalType": "bool",
            "name": "isSdkCallerHelper",
            "type": "bool"
          }
        ],
        "internalType": "struct IKalamangStorage.KalamangConfig",
        "name": "_config",
        "type": "tuple"
      }
    ],
    "name": "createKalamang",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_kalamangId",
        "type": "string"
      }
    ],
    "name": "getKalamangInfo",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "creator",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "kalamangId",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "tokenAddress",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "tokenSymbol",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "maxRecipients",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "claimedRecipients",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isRandom",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "minRandom",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "maxRandom",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "acceptedKYCLevel",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isRequireWhitelist",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "isClaimable",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "totalTokens",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "remainingAmounts",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isActive",
            "type": "bool"
          }
        ],
        "internalType": "struct IKalamangStorage.KalamangInfo",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_kalamangId",
        "type": "string"
      },
      {
        "internalType": "address[]",
        "name": "_whitelist",
        "type": "address[]"
      },
      {
        "internalType": "address",
        "name": "_creator",
        "type": "address"
      }
    ],
    "name": "removeWhitelist",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_kalamangId",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "_creator",
        "type": "address"
      }
    ],
    "name": "unlockKalamang",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_kalamangId",
        "type": "string"
      },
      {
        "internalType": "bool",
        "name": "_isRequireWhitelist",
        "type": "bool"
      },
      {
        "internalType": "address[]",
        "name": "_whitelist",
        "type": "address[]"
      },
      {
        "internalType": "address",
        "name": "_creator",
        "type": "address"
      }
    ],
    "name": "updateWhitelist",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKalamangStorage__factory {
    static readonly abi = _abi;
    static createInterface(): IKalamangStorageInterface {
      return new Interface(_abi) as IKalamangStorageInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKalamangStorage {
      return new Contract(address, _abi, runner) as unknown as IKalamangStorage;
    }
  }
  