/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKAP165, IKAP165Interface } from "../../interfaces/IKAP165.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "name": "supportsInterface",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IKAP165__factory {
    static readonly abi = _abi;
    static createInterface(): IKAP165Interface {
      return new Interface(_abi) as IKAP165Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKAP165 {
      return new Contract(address, _abi, runner) as unknown as IKAP165;
    }
  }
  