/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKAP721Receiver, IKAP721ReceiverInterface } from "../../interfaces/IKAP721Receiver.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "operator",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "onKAP721Received",
    "outputs": [
      {
        "internalType": "bytes4",
        "name": "",
        "type": "bytes4"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKAP721Receiver__factory {
    static readonly abi = _abi;
    static createInterface(): IKAP721ReceiverInterface {
      return new Interface(_abi) as IKAP721ReceiverInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKAP721Receiver {
      return new Contract(address, _abi, runner) as unknown as IKAP721Receiver;
    }
  }
  