/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IKalamangStorage {
      
    export type KalamangConfigStruct = {kalamangId: string, creator: AddressLike, tokenAddress: AddressLike, totalTokens: BigNumberish, maxRecipients: BigNumberish, isRandom: boolean, minRandom: BigNumberish, maxRandom: BigNumberish, acceptedKYCLevel: BigNumberish, isClaimable: boolean, isRequireWhitelist: boolean, whitelist: AddressLike[], isSdkCallerHelper: boolean}

    export type KalamangConfigStructOutput = [kalamangId: string, creator: string, tokenAddress: string, totalTokens: bigint, maxRecipients: bigint, isRandom: boolean, minRandom: bigint, maxRandom: bigint, acceptedKYCLevel: bigint, isClaimable: boolean, isRequireWhitelist: boolean, whitelist: string[], isSdkCallerHelper: boolean] & {kalamangId: string, creator: string, tokenAddress: string, totalTokens: bigint, maxRecipients: bigint, isRandom: boolean, minRandom: bigint, maxRandom: bigint, acceptedKYCLevel: bigint, isClaimable: boolean, isRequireWhitelist: boolean, whitelist: string[], isSdkCallerHelper: boolean }
  

    export type KalamangClaimedHistoryStruct = {claimedAddress: AddressLike, claimedAmount: BigNumberish}

    export type KalamangClaimedHistoryStructOutput = [claimedAddress: string, claimedAmount: bigint] & {claimedAddress: string, claimedAmount: bigint }
  

    export type KalamangInfoStruct = {creator: AddressLike, kalamangId: string, tokenAddress: AddressLike, tokenSymbol: string, maxRecipients: BigNumberish, claimedRecipients: BigNumberish, isRandom: boolean, minRandom: BigNumberish, maxRandom: BigNumberish, acceptedKYCLevel: BigNumberish, isRequireWhitelist: boolean, isClaimable: boolean, totalTokens: BigNumberish, remainingAmounts: BigNumberish, isActive: boolean}

    export type KalamangInfoStructOutput = [creator: string, kalamangId: string, tokenAddress: string, tokenSymbol: string, maxRecipients: bigint, claimedRecipients: bigint, isRandom: boolean, minRandom: bigint, maxRandom: bigint, acceptedKYCLevel: bigint, isRequireWhitelist: boolean, isClaimable: boolean, totalTokens: bigint, remainingAmounts: bigint, isActive: boolean] & {creator: string, kalamangId: string, tokenAddress: string, tokenSymbol: string, maxRecipients: bigint, claimedRecipients: bigint, isRandom: boolean, minRandom: bigint, maxRandom: bigint, acceptedKYCLevel: bigint, isRequireWhitelist: boolean, isClaimable: boolean, totalTokens: bigint, remainingAmounts: bigint, isActive: boolean }
  
    }

  export interface KalamangStorageInterface extends Interface {
    getFunction(nameOrSignature: "abortAllKalamang" | "abortKalamang" | "addWhitelist" | "claimToken" | "createKalamang" | "feeStorage" | "getAllMyKalamangs" | "getKalamangClaimedHistory" | "getKalamangInfo" | "getKalamangWhitelist" | "getKalamangsByPage" | "isAllowAllTokens" | "isClaimable" | "isClaimed" | "isInWhitelist" | "isPaused" | "kalamangController" | "kycBitkubChain" | "owner" | "removeWhitelist" | "sdkTransferRouter" | "setAllowTokenAddress" | "setFeeStorage" | "setIsAllowAllTokens" | "setKalamangController" | "setKycBitkubChain" | "setOwner" | "setPause" | "setSdkTransferRouter" | "totalKalaMangs" | "unlockKalamang" | "updateWhitelist"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'abortAllKalamang', values?: undefined): string;
encodeFunctionData(functionFragment: 'abortKalamang', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'addWhitelist', values: [string, AddressLike[], AddressLike]): string;
encodeFunctionData(functionFragment: 'claimToken', values: [string, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createKalamang', values: [IKalamangStorage.KalamangConfigStruct]): string;
encodeFunctionData(functionFragment: 'feeStorage', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllMyKalamangs', values?: undefined): string;
encodeFunctionData(functionFragment: 'getKalamangClaimedHistory', values: [string]): string;
encodeFunctionData(functionFragment: 'getKalamangInfo', values: [string]): string;
encodeFunctionData(functionFragment: 'getKalamangWhitelist', values: [string]): string;
encodeFunctionData(functionFragment: 'getKalamangsByPage', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isAllowAllTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'isClaimable', values: [string]): string;
encodeFunctionData(functionFragment: 'isClaimed', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'isInWhitelist', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'isPaused', values?: undefined): string;
encodeFunctionData(functionFragment: 'kalamangController', values?: undefined): string;
encodeFunctionData(functionFragment: 'kycBitkubChain', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeWhitelist', values: [string, AddressLike[], AddressLike]): string;
encodeFunctionData(functionFragment: 'sdkTransferRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAllowTokenAddress', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setFeeStorage', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setIsAllowAllTokens', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setKalamangController', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setKycBitkubChain', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPause', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setSdkTransferRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalKalaMangs', values?: undefined): string;
encodeFunctionData(functionFragment: 'unlockKalamang', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'updateWhitelist', values: [string, boolean, AddressLike[], AddressLike]): string;

    decodeFunctionResult(functionFragment: 'abortAllKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'abortKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllMyKalamangs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getKalamangClaimedHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getKalamangInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getKalamangWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getKalamangsByPage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAllowAllTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClaimable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isInWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kalamangController', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kycBitkubChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sdkTransferRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAllowTokenAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setIsAllowAllTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setKalamangController', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setKycBitkubChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSdkTransferRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalKalaMangs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlockKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateWhitelist', data: BytesLike): Result;
  }

  

  export interface KalamangStorage extends BaseContract {
    
    connect(runner?: ContractRunner | null): KalamangStorage;
    waitForDeployment(): Promise<this>;

    interface: KalamangStorageInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    abortAllKalamang: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    abortKalamang: TypedContractMethod<
      [_kalamangId: string, _creator: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    addWhitelist: TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimToken: TypedContractMethod<
      [_kalamangId: string, _claimTokens: BigNumberish, _recipient: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    createKalamang: TypedContractMethod<
      [_config: IKalamangStorage.KalamangConfigStruct, ],
      [void],
      'nonpayable'
    >
    

    
    feeStorage: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAllMyKalamangs: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getKalamangClaimedHistory: TypedContractMethod<
      [_kalamangId: string, ],
      [IKalamangStorage.KalamangClaimedHistoryStructOutput[]],
      'view'
    >
    

    
    getKalamangInfo: TypedContractMethod<
      [_kalamangId: string, ],
      [IKalamangStorage.KalamangInfoStructOutput],
      'view'
    >
    

    
    getKalamangWhitelist: TypedContractMethod<
      [_kalamangId: string, ],
      [string[]],
      'view'
    >
    

    
    getKalamangsByPage: TypedContractMethod<
      [_kalamangOwnerAddress: AddressLike, _page: BigNumberish, _pageLength: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    isAllowAllTokens: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isClaimable: TypedContractMethod<
      [_kalamangId: string, ],
      [boolean],
      'view'
    >
    

    
    isClaimed: TypedContractMethod<
      [_kalamangId: string, _target: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isInWhitelist: TypedContractMethod<
      [_kalamangId: string, _target: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isPaused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    kalamangController: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    kycBitkubChain: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeWhitelist: TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    sdkTransferRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAllowTokenAddress: TypedContractMethod<
      [_tokenAddress: AddressLike, _allow: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeStorage: TypedContractMethod<
      [_feeStorage: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setIsAllowAllTokens: TypedContractMethod<
      [_allow: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setKalamangController: TypedContractMethod<
      [_kalamangController: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setKycBitkubChain: TypedContractMethod<
      [_kycBitkubChain: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setOwner: TypedContractMethod<
      [_owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPause: TypedContractMethod<
      [_isPaused: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setSdkTransferRouter: TypedContractMethod<
      [_sdkTransferRouter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalKalaMangs: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unlockKalamang: TypedContractMethod<
      [_kalamangId: string, _creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateWhitelist: TypedContractMethod<
      [_kalamangId: string, _isRequireWhitelist: boolean, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'abortAllKalamang'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'abortKalamang'): TypedContractMethod<
      [_kalamangId: string, _creator: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addWhitelist'): TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimToken'): TypedContractMethod<
      [_kalamangId: string, _claimTokens: BigNumberish, _recipient: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createKalamang'): TypedContractMethod<
      [_config: IKalamangStorage.KalamangConfigStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeStorage'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAllMyKalamangs'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getKalamangClaimedHistory'): TypedContractMethod<
      [_kalamangId: string, ],
      [IKalamangStorage.KalamangClaimedHistoryStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getKalamangInfo'): TypedContractMethod<
      [_kalamangId: string, ],
      [IKalamangStorage.KalamangInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getKalamangWhitelist'): TypedContractMethod<
      [_kalamangId: string, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getKalamangsByPage'): TypedContractMethod<
      [_kalamangOwnerAddress: AddressLike, _page: BigNumberish, _pageLength: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'isAllowAllTokens'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isClaimable'): TypedContractMethod<
      [_kalamangId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isClaimed'): TypedContractMethod<
      [_kalamangId: string, _target: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isInWhitelist'): TypedContractMethod<
      [_kalamangId: string, _target: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isPaused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'kalamangController'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'kycBitkubChain'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeWhitelist'): TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sdkTransferRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAllowTokenAddress'): TypedContractMethod<
      [_tokenAddress: AddressLike, _allow: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeStorage'): TypedContractMethod<
      [_feeStorage: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setIsAllowAllTokens'): TypedContractMethod<
      [_allow: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setKalamangController'): TypedContractMethod<
      [_kalamangController: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setKycBitkubChain'): TypedContractMethod<
      [_kycBitkubChain: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOwner'): TypedContractMethod<
      [_owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPause'): TypedContractMethod<
      [_isPaused: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSdkTransferRouter'): TypedContractMethod<
      [_sdkTransferRouter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalKalaMangs'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unlockKalamang'): TypedContractMethod<
      [_kalamangId: string, _creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateWhitelist'): TypedContractMethod<
      [_kalamangId: string, _isRequireWhitelist: boolean, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }