/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Authorization', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Authorization__factory>
getContractFactory(name: 'Committee', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Committee__factory>
getContractFactory(name: 'KAP165', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KAP165__factory>
getContractFactory(name: 'KAP721', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KAP721__factory>
getContractFactory(name: 'KYCHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KYCHandler__factory>
getContractFactory(name: 'Pauseable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Pauseable__factory>
getContractFactory(name: 'Calculator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Calculator__factory>
getContractFactory(name: 'AccessController', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AccessController__factory>
getContractFactory(name: 'Authorization', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Authorization__factory>
getContractFactory(name: 'Committee', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Committee__factory>
getContractFactory(name: 'IAdminProjectRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAdminProjectRouter__factory>
getContractFactory(name: 'IKAP20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP20__factory>
getContractFactory(name: 'IKToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKToken__factory>
getContractFactory(name: 'IKYCBitkubChain', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKYCBitkubChain__factory>
getContractFactory(name: 'KalamangKAP20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KalamangKAP20__factory>
getContractFactory(name: 'KAP20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KAP20__factory>
getContractFactory(name: 'KYCHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KYCHandler__factory>
getContractFactory(name: 'Ownable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Ownable__factory>
getContractFactory(name: 'Pausable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Pausable__factory>
getContractFactory(name: 'IAdminProjectRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAdminProjectRouter__factory>
getContractFactory(name: 'IKalamangFeeStorage', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKalamangFeeStorage__factory>
getContractFactory(name: 'IKalamangStorage', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKalamangStorage__factory>
getContractFactory(name: 'IKAP165', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP165__factory>
getContractFactory(name: 'IKAP20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP20__factory>
getContractFactory(name: 'IKAP20S', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP20S__factory>
getContractFactory(name: 'IKAP721', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP721__factory>
getContractFactory(name: 'IKAP721Enumerable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP721Enumerable__factory>
getContractFactory(name: 'IKAP721Metadata', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP721Metadata__factory>
getContractFactory(name: 'IKAP721Receiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP721Receiver__factory>
getContractFactory(name: 'IKYCBitkubChain', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKYCBitkubChain__factory>
getContractFactory(name: 'ISdkTransferRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISdkTransferRouter__factory>
getContractFactory(name: 'KalamangController', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KalamangController__factory>
getContractFactory(name: 'KalamangFeeStorage', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KalamangFeeStorage__factory>
getContractFactory(name: 'KalamangWashing', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KalamangWashing__factory>
getContractFactory(name: 'KalamangStorage', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KalamangStorage__factory>
getContractFactory(name: 'AccessController', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AccessController__factory>
getContractFactory(name: 'Authorization', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Authorization__factory>
getContractFactory(name: 'Committee', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Committee__factory>
getContractFactory(name: 'IAdminProjectRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAdminProjectRouter__factory>
getContractFactory(name: 'IKAP20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKAP20__factory>
getContractFactory(name: 'IKToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKToken__factory>
getContractFactory(name: 'IKYCBitkubChain', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKYCBitkubChain__factory>
getContractFactory(name: 'KAP20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KAP20__factory>
getContractFactory(name: 'KKUB', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KKUB__factory>
getContractFactory(name: 'KYCHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KYCHandler__factory>
getContractFactory(name: 'Ownable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Ownable__factory>
getContractFactory(name: 'Pausable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Pausable__factory>
getContractFactory(name: 'RandomRateExperiment', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RandomRateExperiment__factory>
getContractFactory(name: 'TheOasis', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TheOasis__factory>

  getContractAt(name: 'Authorization', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Authorization>
getContractAt(name: 'Committee', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Committee>
getContractAt(name: 'KAP165', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KAP165>
getContractAt(name: 'KAP721', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KAP721>
getContractAt(name: 'KYCHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KYCHandler>
getContractAt(name: 'Pauseable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Pauseable>
getContractAt(name: 'Calculator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Calculator>
getContractAt(name: 'AccessController', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AccessController>
getContractAt(name: 'Authorization', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Authorization>
getContractAt(name: 'Committee', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Committee>
getContractAt(name: 'IAdminProjectRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAdminProjectRouter>
getContractAt(name: 'IKAP20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP20>
getContractAt(name: 'IKToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKToken>
getContractAt(name: 'IKYCBitkubChain', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKYCBitkubChain>
getContractAt(name: 'KalamangKAP20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KalamangKAP20>
getContractAt(name: 'KAP20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KAP20>
getContractAt(name: 'KYCHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KYCHandler>
getContractAt(name: 'Ownable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Ownable>
getContractAt(name: 'Pausable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Pausable>
getContractAt(name: 'IAdminProjectRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAdminProjectRouter>
getContractAt(name: 'IKalamangFeeStorage', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKalamangFeeStorage>
getContractAt(name: 'IKalamangStorage', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKalamangStorage>
getContractAt(name: 'IKAP165', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP165>
getContractAt(name: 'IKAP20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP20>
getContractAt(name: 'IKAP20S', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP20S>
getContractAt(name: 'IKAP721', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP721>
getContractAt(name: 'IKAP721Enumerable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP721Enumerable>
getContractAt(name: 'IKAP721Metadata', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP721Metadata>
getContractAt(name: 'IKAP721Receiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP721Receiver>
getContractAt(name: 'IKYCBitkubChain', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKYCBitkubChain>
getContractAt(name: 'ISdkTransferRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISdkTransferRouter>
getContractAt(name: 'KalamangController', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KalamangController>
getContractAt(name: 'KalamangFeeStorage', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KalamangFeeStorage>
getContractAt(name: 'KalamangWashing', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KalamangWashing>
getContractAt(name: 'KalamangStorage', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KalamangStorage>
getContractAt(name: 'AccessController', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AccessController>
getContractAt(name: 'Authorization', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Authorization>
getContractAt(name: 'Committee', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Committee>
getContractAt(name: 'IAdminProjectRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAdminProjectRouter>
getContractAt(name: 'IKAP20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKAP20>
getContractAt(name: 'IKToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKToken>
getContractAt(name: 'IKYCBitkubChain', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKYCBitkubChain>
getContractAt(name: 'KAP20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KAP20>
getContractAt(name: 'KKUB', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KKUB>
getContractAt(name: 'KYCHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KYCHandler>
getContractAt(name: 'Ownable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Ownable>
getContractAt(name: 'Pausable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Pausable>
getContractAt(name: 'RandomRateExperiment', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RandomRateExperiment>
getContractAt(name: 'TheOasis', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TheOasis>

  deployContract(name: 'Authorization', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Authorization>
deployContract(name: 'Committee', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Committee>
deployContract(name: 'KAP165', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KAP165>
deployContract(name: 'KAP721', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KAP721>
deployContract(name: 'KYCHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KYCHandler>
deployContract(name: 'Pauseable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pauseable>
deployContract(name: 'Calculator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Calculator>
deployContract(name: 'AccessController', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AccessController>
deployContract(name: 'Authorization', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Authorization>
deployContract(name: 'Committee', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Committee>
deployContract(name: 'IAdminProjectRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAdminProjectRouter>
deployContract(name: 'IKAP20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP20>
deployContract(name: 'IKToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKToken>
deployContract(name: 'IKYCBitkubChain', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKYCBitkubChain>
deployContract(name: 'KalamangKAP20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangKAP20>
deployContract(name: 'KAP20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KAP20>
deployContract(name: 'KYCHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KYCHandler>
deployContract(name: 'Ownable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'Pausable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pausable>
deployContract(name: 'IAdminProjectRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAdminProjectRouter>
deployContract(name: 'IKalamangFeeStorage', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKalamangFeeStorage>
deployContract(name: 'IKalamangStorage', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKalamangStorage>
deployContract(name: 'IKAP165', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP165>
deployContract(name: 'IKAP20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP20>
deployContract(name: 'IKAP20S', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP20S>
deployContract(name: 'IKAP721', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP721>
deployContract(name: 'IKAP721Enumerable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP721Enumerable>
deployContract(name: 'IKAP721Metadata', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP721Metadata>
deployContract(name: 'IKAP721Receiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP721Receiver>
deployContract(name: 'IKYCBitkubChain', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKYCBitkubChain>
deployContract(name: 'ISdkTransferRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISdkTransferRouter>
deployContract(name: 'KalamangController', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangController>
deployContract(name: 'KalamangFeeStorage', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangFeeStorage>
deployContract(name: 'KalamangWashing', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangWashing>
deployContract(name: 'KalamangStorage', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangStorage>
deployContract(name: 'AccessController', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AccessController>
deployContract(name: 'Authorization', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Authorization>
deployContract(name: 'Committee', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Committee>
deployContract(name: 'IAdminProjectRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAdminProjectRouter>
deployContract(name: 'IKAP20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP20>
deployContract(name: 'IKToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKToken>
deployContract(name: 'IKYCBitkubChain', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKYCBitkubChain>
deployContract(name: 'KAP20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KAP20>
deployContract(name: 'KKUB', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KKUB>
deployContract(name: 'KYCHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KYCHandler>
deployContract(name: 'Ownable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'Pausable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pausable>
deployContract(name: 'RandomRateExperiment', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RandomRateExperiment>
deployContract(name: 'TheOasis', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TheOasis>

  deployContract(name: 'Authorization', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Authorization>
deployContract(name: 'Committee', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Committee>
deployContract(name: 'KAP165', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KAP165>
deployContract(name: 'KAP721', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KAP721>
deployContract(name: 'KYCHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KYCHandler>
deployContract(name: 'Pauseable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pauseable>
deployContract(name: 'Calculator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Calculator>
deployContract(name: 'AccessController', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AccessController>
deployContract(name: 'Authorization', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Authorization>
deployContract(name: 'Committee', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Committee>
deployContract(name: 'IAdminProjectRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAdminProjectRouter>
deployContract(name: 'IKAP20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP20>
deployContract(name: 'IKToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKToken>
deployContract(name: 'IKYCBitkubChain', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKYCBitkubChain>
deployContract(name: 'KalamangKAP20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangKAP20>
deployContract(name: 'KAP20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KAP20>
deployContract(name: 'KYCHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KYCHandler>
deployContract(name: 'Ownable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'Pausable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pausable>
deployContract(name: 'IAdminProjectRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAdminProjectRouter>
deployContract(name: 'IKalamangFeeStorage', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKalamangFeeStorage>
deployContract(name: 'IKalamangStorage', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKalamangStorage>
deployContract(name: 'IKAP165', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP165>
deployContract(name: 'IKAP20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP20>
deployContract(name: 'IKAP20S', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP20S>
deployContract(name: 'IKAP721', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP721>
deployContract(name: 'IKAP721Enumerable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP721Enumerable>
deployContract(name: 'IKAP721Metadata', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP721Metadata>
deployContract(name: 'IKAP721Receiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP721Receiver>
deployContract(name: 'IKYCBitkubChain', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKYCBitkubChain>
deployContract(name: 'ISdkTransferRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISdkTransferRouter>
deployContract(name: 'KalamangController', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangController>
deployContract(name: 'KalamangFeeStorage', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangFeeStorage>
deployContract(name: 'KalamangWashing', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangWashing>
deployContract(name: 'KalamangStorage', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KalamangStorage>
deployContract(name: 'AccessController', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AccessController>
deployContract(name: 'Authorization', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Authorization>
deployContract(name: 'Committee', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Committee>
deployContract(name: 'IAdminProjectRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAdminProjectRouter>
deployContract(name: 'IKAP20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKAP20>
deployContract(name: 'IKToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKToken>
deployContract(name: 'IKYCBitkubChain', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKYCBitkubChain>
deployContract(name: 'KAP20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KAP20>
deployContract(name: 'KKUB', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KKUB>
deployContract(name: 'KYCHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KYCHandler>
deployContract(name: 'Ownable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'Pausable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Pausable>
deployContract(name: 'RandomRateExperiment', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RandomRateExperiment>
deployContract(name: 'TheOasis', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TheOasis>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  