/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as exampleKap20Sol from './ExampleKAP20.sol/index.js';
export * as kkubSol from './KKUB.sol/index.js';
export * as kalamangKap721Sol from './KalamangKAP721.sol/index.js';
export * as abstracts from './abstracts/index.js';
export * as caculatorSol from './caculator.sol/index.js';
export * as interfaces from './interfaces/index.js';
export * as kalamangControllerSol from './kalamangController.sol/index.js';
export * as kalamangFeeStorageSol from './kalamangFeeStorage.sol/index.js';
export * as kalamangStorageSol from './kalamangStorage.sol/index.js';
export * as randomSol from './random.sol/index.js';
export { TheOasis__factory } from './TheOasis__factory.js';