/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KalamangFeeStorageInterface extends Interface {
    getFunction(nameOrSignature: "fee" | "getFee" | "setFee" | "setOwner" | "withdrawFee"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ChangeFee" | "WithdrawFee"): EventFragment;

    encodeFunctionData(functionFragment: 'fee', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawFee', values: [AddressLike[]]): string;

    decodeFunctionResult(functionFragment: 'fee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFee', data: BytesLike): Result;
  }

  
    export namespace ChangeFeeEvent {
      export type InputTuple = [caller: AddressLike, fee: BigNumberish];
      export type OutputTuple = [caller: string, fee: bigint];
      export interface OutputObject {caller: string, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawFeeEvent {
      export type InputTuple = [caller: AddressLike];
      export type OutputTuple = [caller: string];
      export interface OutputObject {caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KalamangFeeStorage extends BaseContract {
    
    connect(runner?: ContractRunner | null): KalamangFeeStorage;
    waitForDeployment(): Promise<this>;

    interface: KalamangFeeStorageInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    fee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setFee: TypedContractMethod<
      [_fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setOwner: TypedContractMethod<
      [_owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawFee: TypedContractMethod<
      [_tokenAddresses: AddressLike[], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'fee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setFee'): TypedContractMethod<
      [_fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOwner'): TypedContractMethod<
      [_owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFee'): TypedContractMethod<
      [_tokenAddresses: AddressLike[], ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ChangeFee'): TypedContractEvent<ChangeFeeEvent.InputTuple, ChangeFeeEvent.OutputTuple, ChangeFeeEvent.OutputObject>;
getEvent(key: 'WithdrawFee'): TypedContractEvent<WithdrawFeeEvent.InputTuple, WithdrawFeeEvent.OutputTuple, WithdrawFeeEvent.OutputObject>;

    filters: {
      
      'ChangeFee(address,uint256)': TypedContractEvent<ChangeFeeEvent.InputTuple, ChangeFeeEvent.OutputTuple, ChangeFeeEvent.OutputObject>;
      ChangeFee: TypedContractEvent<ChangeFeeEvent.InputTuple, ChangeFeeEvent.OutputTuple, ChangeFeeEvent.OutputObject>;
    

      'WithdrawFee(address)': TypedContractEvent<WithdrawFeeEvent.InputTuple, WithdrawFeeEvent.OutputTuple, WithdrawFeeEvent.OutputObject>;
      WithdrawFee: TypedContractEvent<WithdrawFeeEvent.InputTuple, WithdrawFeeEvent.OutputTuple, WithdrawFeeEvent.OutputObject>;
    
    };
  }