/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KalamangControllerInterface extends Interface {
    getFunction(nameOrSignature: "abortKalamang" | "abortKalamangBySdk" | "addWhitelist" | "addWhitelistBySdk" | "claimToken" | "claimTokenBySdk" | "createKalamang" | "createKalamangBySdk" | "isPaused" | "kalamangStorage" | "owner" | "randomSetSize" | "removeWhitelist" | "removeWhitelistBySdk" | "sdkCallHelperRouter" | "setPause" | "setSdkCallHelperRouter" | "setkalamangStorage" | "unlockKalamang" | "unlockKalamangBySdk" | "updateWhitelist" | "updateWhitelistBySdk"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "KalamangAborted" | "KalamangCreated" | "KalamangUnlocked" | "TokenClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'abortKalamang', values: [string]): string;
encodeFunctionData(functionFragment: 'abortKalamangBySdk', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'addWhitelist', values: [string, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'addWhitelistBySdk', values: [string, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'claimToken', values: [string]): string;
encodeFunctionData(functionFragment: 'claimTokenBySdk', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'createKalamang', values: [AddressLike, BigNumberish, BigNumberish, boolean, BigNumberish, BigNumberish, BigNumberish, boolean, AddressLike[], boolean]): string;
encodeFunctionData(functionFragment: 'createKalamangBySdk', values: [AddressLike, BigNumberish, BigNumberish, boolean, BigNumberish, BigNumberish, BigNumberish, boolean, BytesLike, boolean, AddressLike]): string;
encodeFunctionData(functionFragment: 'isPaused', values?: undefined): string;
encodeFunctionData(functionFragment: 'kalamangStorage', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'randomSetSize', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeWhitelist', values: [string, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'removeWhitelistBySdk', values: [string, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'sdkCallHelperRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPause', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setSdkCallHelperRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setkalamangStorage', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unlockKalamang', values: [string]): string;
encodeFunctionData(functionFragment: 'unlockKalamangBySdk', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'updateWhitelist', values: [string, boolean, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'updateWhitelistBySdk', values: [string, boolean, BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'abortKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'abortKalamangBySdk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addWhitelistBySdk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTokenBySdk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createKalamangBySdk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kalamangStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'randomSetSize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeWhitelistBySdk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sdkCallHelperRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSdkCallHelperRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setkalamangStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlockKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlockKalamangBySdk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateWhitelistBySdk', data: BytesLike): Result;
  }

  
    export namespace KalamangAbortedEvent {
      export type InputTuple = [kalamangId: string, returnAmount: BigNumberish];
      export type OutputTuple = [kalamangId: string, returnAmount: bigint];
      export interface OutputObject {kalamangId: string, returnAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace KalamangCreatedEvent {
      export type InputTuple = [kalamangId: string, creator: AddressLike, totalTokens: BigNumberish, maxRecipients: BigNumberish];
      export type OutputTuple = [kalamangId: string, creator: string, totalTokens: bigint, maxRecipients: bigint];
      export interface OutputObject {kalamangId: string, creator: string, totalTokens: bigint, maxRecipients: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace KalamangUnlockedEvent {
      export type InputTuple = [kalamangId: string];
      export type OutputTuple = [kalamangId: string];
      export interface OutputObject {kalamangId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenClaimedEvent {
      export type InputTuple = [kalamangId: string, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [kalamangId: string, recipient: string, amount: bigint];
      export interface OutputObject {kalamangId: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KalamangController extends BaseContract {
    
    connect(runner?: ContractRunner | null): KalamangController;
    waitForDeployment(): Promise<this>;

    interface: KalamangControllerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    abortKalamang: TypedContractMethod<
      [_kalamangId: string, ],
      [void],
      'nonpayable'
    >
    

    
    abortKalamangBySdk: TypedContractMethod<
      [_kalamangId: string, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addWhitelist: TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    addWhitelistBySdk: TypedContractMethod<
      [_kalamangId: string, _whitelist: BytesLike, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimToken: TypedContractMethod<
      [_kalamangId: string, ],
      [void],
      'nonpayable'
    >
    

    
    claimTokenBySdk: TypedContractMethod<
      [_kalamangId: string, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    createKalamang: TypedContractMethod<
      [_tokenAddress: AddressLike, _totalTokens: BigNumberish, _maxRecipients: BigNumberish, _isRandom: boolean, _minRandom: BigNumberish, _maxRandom: BigNumberish, _acceptedKYCLevel: BigNumberish, _isRequireWhitelist: boolean, _whitelist: AddressLike[], _isClaimable: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    createKalamangBySdk: TypedContractMethod<
      [_tokenAddress: AddressLike, _totalTokens: BigNumberish, _maxRecipients: BigNumberish, _isRandom: boolean, _minRandom: BigNumberish, _maxRandom: BigNumberish, _acceptedKYCLevel: BigNumberish, _isRequireWhitelist: boolean, _whitelist: BytesLike, _isClaimable: boolean, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isPaused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    kalamangStorage: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    randomSetSize: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    removeWhitelist: TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    removeWhitelistBySdk: TypedContractMethod<
      [_kalamangId: string, _whitelist: BytesLike, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    sdkCallHelperRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setPause: TypedContractMethod<
      [_isPaused: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setSdkCallHelperRouter: TypedContractMethod<
      [_sdkCallHelperRouter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setkalamangStorage: TypedContractMethod<
      [_kalamangStorage: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unlockKalamang: TypedContractMethod<
      [_kalamangId: string, ],
      [void],
      'nonpayable'
    >
    

    
    unlockKalamangBySdk: TypedContractMethod<
      [_kalamangId: string, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateWhitelist: TypedContractMethod<
      [_kalamangId: string, _isRequireWhitelist: boolean, _whitelist: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    updateWhitelistBySdk: TypedContractMethod<
      [_kalamangId: string, _isRequireWhitelist: boolean, _whitelist: BytesLike, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'abortKalamang'): TypedContractMethod<
      [_kalamangId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'abortKalamangBySdk'): TypedContractMethod<
      [_kalamangId: string, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addWhitelist'): TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addWhitelistBySdk'): TypedContractMethod<
      [_kalamangId: string, _whitelist: BytesLike, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimToken'): TypedContractMethod<
      [_kalamangId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTokenBySdk'): TypedContractMethod<
      [_kalamangId: string, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createKalamang'): TypedContractMethod<
      [_tokenAddress: AddressLike, _totalTokens: BigNumberish, _maxRecipients: BigNumberish, _isRandom: boolean, _minRandom: BigNumberish, _maxRandom: BigNumberish, _acceptedKYCLevel: BigNumberish, _isRequireWhitelist: boolean, _whitelist: AddressLike[], _isClaimable: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createKalamangBySdk'): TypedContractMethod<
      [_tokenAddress: AddressLike, _totalTokens: BigNumberish, _maxRecipients: BigNumberish, _isRandom: boolean, _minRandom: BigNumberish, _maxRandom: BigNumberish, _acceptedKYCLevel: BigNumberish, _isRequireWhitelist: boolean, _whitelist: BytesLike, _isClaimable: boolean, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isPaused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'kalamangStorage'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'randomSetSize'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'removeWhitelist'): TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeWhitelistBySdk'): TypedContractMethod<
      [_kalamangId: string, _whitelist: BytesLike, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sdkCallHelperRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setPause'): TypedContractMethod<
      [_isPaused: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSdkCallHelperRouter'): TypedContractMethod<
      [_sdkCallHelperRouter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setkalamangStorage'): TypedContractMethod<
      [_kalamangStorage: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unlockKalamang'): TypedContractMethod<
      [_kalamangId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unlockKalamangBySdk'): TypedContractMethod<
      [_kalamangId: string, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateWhitelist'): TypedContractMethod<
      [_kalamangId: string, _isRequireWhitelist: boolean, _whitelist: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateWhitelistBySdk'): TypedContractMethod<
      [_kalamangId: string, _isRequireWhitelist: boolean, _whitelist: BytesLike, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'KalamangAborted'): TypedContractEvent<KalamangAbortedEvent.InputTuple, KalamangAbortedEvent.OutputTuple, KalamangAbortedEvent.OutputObject>;
getEvent(key: 'KalamangCreated'): TypedContractEvent<KalamangCreatedEvent.InputTuple, KalamangCreatedEvent.OutputTuple, KalamangCreatedEvent.OutputObject>;
getEvent(key: 'KalamangUnlocked'): TypedContractEvent<KalamangUnlockedEvent.InputTuple, KalamangUnlockedEvent.OutputTuple, KalamangUnlockedEvent.OutputObject>;
getEvent(key: 'TokenClaimed'): TypedContractEvent<TokenClaimedEvent.InputTuple, TokenClaimedEvent.OutputTuple, TokenClaimedEvent.OutputObject>;

    filters: {
      
      'KalamangAborted(string,uint256)': TypedContractEvent<KalamangAbortedEvent.InputTuple, KalamangAbortedEvent.OutputTuple, KalamangAbortedEvent.OutputObject>;
      KalamangAborted: TypedContractEvent<KalamangAbortedEvent.InputTuple, KalamangAbortedEvent.OutputTuple, KalamangAbortedEvent.OutputObject>;
    

      'KalamangCreated(string,address,uint256,uint256)': TypedContractEvent<KalamangCreatedEvent.InputTuple, KalamangCreatedEvent.OutputTuple, KalamangCreatedEvent.OutputObject>;
      KalamangCreated: TypedContractEvent<KalamangCreatedEvent.InputTuple, KalamangCreatedEvent.OutputTuple, KalamangCreatedEvent.OutputObject>;
    

      'KalamangUnlocked(string)': TypedContractEvent<KalamangUnlockedEvent.InputTuple, KalamangUnlockedEvent.OutputTuple, KalamangUnlockedEvent.OutputObject>;
      KalamangUnlocked: TypedContractEvent<KalamangUnlockedEvent.InputTuple, KalamangUnlockedEvent.OutputTuple, KalamangUnlockedEvent.OutputObject>;
    

      'TokenClaimed(string,address,uint256)': TypedContractEvent<TokenClaimedEvent.InputTuple, TokenClaimedEvent.OutputTuple, TokenClaimedEvent.OutputObject>;
      TokenClaimed: TypedContractEvent<TokenClaimedEvent.InputTuple, TokenClaimedEvent.OutputTuple, TokenClaimedEvent.OutputObject>;
    
    };
  }