/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KalamangKAP20Interface extends Interface {
    getFunction(nameOrSignature: "PROJECT" | "acceptedKYCLevel" | "activateOnlyKYCAddress" | "adminApprove" | "adminProjectRouter" | "adminTransfer" | "allowance" | "approve" | "balanceOf" | "committee" | "decimals" | "decreaseAllowance" | "externalTransfer" | "increaseAllowance" | "internalTransfer" | "isActivatedOnlyKYCAddress" | "kyc" | "mint" | "name" | "paused" | "setAcceptedKYCLevel" | "setAdminProjectRouter" | "setCommittee" | "setKYC" | "setTransferRouter" | "symbol" | "totalSupply" | "transfer" | "transferFrom" | "transferRouter"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminProjectRouterSet" | "Approval" | "CommitteeSet" | "Paused" | "Transfer" | "TransferRouterSet" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'PROJECT', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptedKYCLevel', values?: undefined): string;
encodeFunctionData(functionFragment: 'activateOnlyKYCAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'adminApprove', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'adminProjectRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'adminTransfer', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'committee', values?: undefined): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'decreaseAllowance', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'externalTransfer', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'increaseAllowance', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'internalTransfer', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isActivatedOnlyKYCAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'kyc', values?: undefined): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAcceptedKYCLevel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setAdminProjectRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setCommittee', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setKYC', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTransferRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferRouter', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'PROJECT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptedKYCLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activateOnlyKYCAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminApprove', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminProjectRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'committee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decreaseAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'externalTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increaseAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'internalTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActivatedOnlyKYCAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAcceptedKYCLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAdminProjectRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCommittee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setKYC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTransferRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferRouter', data: BytesLike): Result;
  }

  
    export namespace AdminProjectRouterSetEvent {
      export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike, caller: AddressLike];
      export type OutputTuple = [oldAdmin: string, newAdmin: string, caller: string];
      export interface OutputObject {oldAdmin: string, newAdmin: string, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommitteeSetEvent {
      export type InputTuple = [oldCommittee: AddressLike, newCommittee: AddressLike, caller: AddressLike];
      export type OutputTuple = [oldCommittee: string, newCommittee: string, caller: string];
      export interface OutputObject {oldCommittee: string, newCommittee: string, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferRouterSetEvent {
      export type InputTuple = [oldTransferRouter: AddressLike, newTransferRouter: AddressLike, caller: AddressLike];
      export type OutputTuple = [oldTransferRouter: string, newTransferRouter: string, caller: string];
      export interface OutputObject {oldTransferRouter: string, newTransferRouter: string, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KalamangKAP20 extends BaseContract {
    
    connect(runner?: ContractRunner | null): KalamangKAP20;
    waitForDeployment(): Promise<this>;

    interface: KalamangKAP20Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    PROJECT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    acceptedKYCLevel: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activateOnlyKYCAddress: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    adminApprove: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    adminProjectRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    adminTransfer: TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    committee: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decreaseAllowance: TypedContractMethod<
      [spender: AddressLike, subtractedValue: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    externalTransfer: TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    increaseAllowance: TypedContractMethod<
      [spender: AddressLike, addedValue: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    internalTransfer: TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    isActivatedOnlyKYCAddress: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    kyc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [_to: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setAcceptedKYCLevel: TypedContractMethod<
      [_kycLevel: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setAdminProjectRouter: TypedContractMethod<
      [_adminProjectRouter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setCommittee: TypedContractMethod<
      [_committee: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setKYC: TypedContractMethod<
      [_kyc: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTransferRouter: TypedContractMethod<
      [_transferRouter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'PROJECT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'acceptedKYCLevel'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activateOnlyKYCAddress'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminApprove'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminProjectRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'adminTransfer'): TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'committee'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decreaseAllowance'): TypedContractMethod<
      [spender: AddressLike, subtractedValue: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'externalTransfer'): TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'increaseAllowance'): TypedContractMethod<
      [spender: AddressLike, addedValue: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'internalTransfer'): TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isActivatedOnlyKYCAddress'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'kyc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [_to: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setAcceptedKYCLevel'): TypedContractMethod<
      [_kycLevel: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAdminProjectRouter'): TypedContractMethod<
      [_adminProjectRouter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCommittee'): TypedContractMethod<
      [_committee: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setKYC'): TypedContractMethod<
      [_kyc: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTransferRouter'): TypedContractMethod<
      [_transferRouter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AdminProjectRouterSet'): TypedContractEvent<AdminProjectRouterSetEvent.InputTuple, AdminProjectRouterSetEvent.OutputTuple, AdminProjectRouterSetEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'CommitteeSet'): TypedContractEvent<CommitteeSetEvent.InputTuple, CommitteeSetEvent.OutputTuple, CommitteeSetEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TransferRouterSet'): TypedContractEvent<TransferRouterSetEvent.InputTuple, TransferRouterSetEvent.OutputTuple, TransferRouterSetEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'AdminProjectRouterSet(address,address,address)': TypedContractEvent<AdminProjectRouterSetEvent.InputTuple, AdminProjectRouterSetEvent.OutputTuple, AdminProjectRouterSetEvent.OutputObject>;
      AdminProjectRouterSet: TypedContractEvent<AdminProjectRouterSetEvent.InputTuple, AdminProjectRouterSetEvent.OutputTuple, AdminProjectRouterSetEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'CommitteeSet(address,address,address)': TypedContractEvent<CommitteeSetEvent.InputTuple, CommitteeSetEvent.OutputTuple, CommitteeSetEvent.OutputObject>;
      CommitteeSet: TypedContractEvent<CommitteeSetEvent.InputTuple, CommitteeSetEvent.OutputTuple, CommitteeSetEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TransferRouterSet(address,address,address)': TypedContractEvent<TransferRouterSetEvent.InputTuple, TransferRouterSetEvent.OutputTuple, TransferRouterSetEvent.OutputObject>;
      TransferRouterSet: TypedContractEvent<TransferRouterSetEvent.InputTuple, TransferRouterSetEvent.OutputTuple, TransferRouterSetEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }