/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RandomRateExperimentInterface extends Interface {
    getFunction(nameOrSignature: "randomCeption" | "randomNormal" | "randomNormal2" | "randomRateControl" | "randomRateControl2"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'randomCeption', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'randomNormal', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'randomNormal2', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'randomRateControl', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'randomRateControl2', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'randomCeption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'randomNormal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'randomNormal2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'randomRateControl', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'randomRateControl2', data: BytesLike): Result;
  }

  

  export interface RandomRateExperiment extends BaseContract {
    
    connect(runner?: ContractRunner | null): RandomRateExperiment;
    waitForDeployment(): Promise<this>;

    interface: RandomRateExperimentInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    randomCeption: TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    randomNormal: TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    randomNormal2: TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    randomRateControl: TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    randomRateControl2: TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'randomCeption'): TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'randomNormal'): TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'randomNormal2'): TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'randomRateControl'): TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'randomRateControl2'): TypedContractMethod<
      [total: BigNumberish, amount: BigNumberish, ],
      [bigint[]],
      'view'
    >;

    

    filters: {
      
    };
  }