/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { KAP165, KAP165Interface } from "../../abstracts/KAP165.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "name": "supportsInterface",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class KAP165__factory {
    static readonly abi = _abi;
    static createInterface(): KAP165Interface {
      return new Interface(_abi) as KAP165Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): KAP165 {
      return new Contract(address, _abi, runner) as unknown as KAP165;
    }
  }
  