/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { Pauseable, PauseableInterface } from "../../abstracts/Pauseable.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "Paused",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "Unpaused",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "paused",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class Pauseable__factory {
    static readonly abi = _abi;
    static createInterface(): PauseableInterface {
      return new Interface(_abi) as PauseableInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): Pauseable {
      return new Contract(address, _abi, runner) as unknown as Pauseable;
    }
  }
  