/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AuthorizationInterface extends Interface {
    getFunction(nameOrSignature: "adminRouter" | "project" | "setAdmin" | "setProject" | "setTransferRouter" | "transferRouter"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SetAdmin"): EventFragment;

    encodeFunctionData(functionFragment: 'adminRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'project', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setProject', values: [string]): string;
encodeFunctionData(functionFragment: 'setTransferRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferRouter', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'adminRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'project', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTransferRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferRouter', data: BytesLike): Result;
  }

  
    export namespace SetAdminEvent {
      export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike, caller: AddressLike];
      export type OutputTuple = [oldAdmin: string, newAdmin: string, caller: string];
      export interface OutputObject {oldAdmin: string, newAdmin: string, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Authorization extends BaseContract {
    
    connect(runner?: ContractRunner | null): Authorization;
    waitForDeployment(): Promise<this>;

    interface: AuthorizationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    adminRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    project: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAdmin: TypedContractMethod<
      [_adminRouter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setProject: TypedContractMethod<
      [_project: string, ],
      [void],
      'nonpayable'
    >
    

    
    setTransferRouter: TypedContractMethod<
      [_transferRouter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'adminRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'project'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAdmin'): TypedContractMethod<
      [_adminRouter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProject'): TypedContractMethod<
      [_project: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTransferRouter'): TypedContractMethod<
      [_transferRouter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'SetAdmin'): TypedContractEvent<SetAdminEvent.InputTuple, SetAdminEvent.OutputTuple, SetAdminEvent.OutputObject>;

    filters: {
      
      'SetAdmin(address,address,address)': TypedContractEvent<SetAdminEvent.InputTuple, SetAdminEvent.OutputTuple, SetAdminEvent.OutputObject>;
      SetAdmin: TypedContractEvent<SetAdminEvent.InputTuple, SetAdminEvent.OutputTuple, SetAdminEvent.OutputObject>;
    
    };
  }