/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KYCHandlerInterface extends Interface {
    getFunction(nameOrSignature: "acceptedKycLevel" | "isActivatedOnlyKycAddress" | "kyc"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'acceptedKycLevel', values?: undefined): string;
encodeFunctionData(functionFragment: 'isActivatedOnlyKycAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'kyc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'acceptedKycLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActivatedOnlyKycAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kyc', data: BytesLike): Result;
  }

  

  export interface KYCHandler extends BaseContract {
    
    connect(runner?: ContractRunner | null): KYCHandler;
    waitForDeployment(): Promise<this>;

    interface: KYCHandlerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptedKycLevel: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isActivatedOnlyKycAddress: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    kyc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptedKycLevel'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isActivatedOnlyKycAddress'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'kyc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }