/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { KYCHandler, KYCHandlerInterface } from "../../ExampleKAP20.sol/KYCHandler.js";

  const _abi = [
  {
    "inputs": [],
    "name": "acceptedKYCLevel",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "isActivatedOnlyKYCAddress",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "kyc",
    "outputs": [
      {
        "internalType": "contract IKYCBitkubChain",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class KYCHandler__factory {
    static readonly abi = _abi;
    static createInterface(): KYCHandlerInterface {
      return new Interface(_abi) as KYCHandlerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): KYCHandler {
      return new Contract(address, _abi, runner) as unknown as KYCHandler;
    }
  }
  