/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IKalamangStorage {
      
    export type KalamangConfigStruct = {kalamangId: string, creator: AddressLike, tokenAddress: AddressLike, totalTokens: BigNumberish, maxRecipients: BigNumberish, isRandom: boolean, minRandom: BigNumberish, maxRandom: BigNumberish, acceptedKYCLevel: BigNumberish, isClaimable: boolean, isRequireWhitelist: boolean, whitelist: AddressLike[], isSdkCallerHelper: boolean}

    export type KalamangConfigStructOutput = [kalamangId: string, creator: string, tokenAddress: string, totalTokens: bigint, maxRecipients: bigint, isRandom: boolean, minRandom: bigint, maxRandom: bigint, acceptedKYCLevel: bigint, isClaimable: boolean, isRequireWhitelist: boolean, whitelist: string[], isSdkCallerHelper: boolean] & {kalamangId: string, creator: string, tokenAddress: string, totalTokens: bigint, maxRecipients: bigint, isRandom: boolean, minRandom: bigint, maxRandom: bigint, acceptedKYCLevel: bigint, isClaimable: boolean, isRequireWhitelist: boolean, whitelist: string[], isSdkCallerHelper: boolean }
  

    export type KalamangInfoStruct = {creator: AddressLike, kalamangId: string, tokenAddress: AddressLike, tokenSymbol: string, maxRecipients: BigNumberish, claimedRecipients: BigNumberish, isRandom: boolean, minRandom: BigNumberish, maxRandom: BigNumberish, acceptedKYCLevel: BigNumberish, isRequireWhitelist: boolean, isClaimable: boolean, totalTokens: BigNumberish, remainingAmounts: BigNumberish, isActive: boolean}

    export type KalamangInfoStructOutput = [creator: string, kalamangId: string, tokenAddress: string, tokenSymbol: string, maxRecipients: bigint, claimedRecipients: bigint, isRandom: boolean, minRandom: bigint, maxRandom: bigint, acceptedKYCLevel: bigint, isRequireWhitelist: boolean, isClaimable: boolean, totalTokens: bigint, remainingAmounts: bigint, isActive: boolean] & {creator: string, kalamangId: string, tokenAddress: string, tokenSymbol: string, maxRecipients: bigint, claimedRecipients: bigint, isRandom: boolean, minRandom: bigint, maxRandom: bigint, acceptedKYCLevel: bigint, isRequireWhitelist: boolean, isClaimable: boolean, totalTokens: bigint, remainingAmounts: bigint, isActive: boolean }
  
    }

  export interface IKalamangStorageInterface extends Interface {
    getFunction(nameOrSignature: "abortKalamang" | "addWhitelist" | "claimToken" | "createKalamang" | "getKalamangInfo" | "removeWhitelist" | "unlockKalamang" | "updateWhitelist"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'abortKalamang', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'addWhitelist', values: [string, AddressLike[], AddressLike]): string;
encodeFunctionData(functionFragment: 'claimToken', values: [string, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createKalamang', values: [IKalamangStorage.KalamangConfigStruct]): string;
encodeFunctionData(functionFragment: 'getKalamangInfo', values: [string]): string;
encodeFunctionData(functionFragment: 'removeWhitelist', values: [string, AddressLike[], AddressLike]): string;
encodeFunctionData(functionFragment: 'unlockKalamang', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'updateWhitelist', values: [string, boolean, AddressLike[], AddressLike]): string;

    decodeFunctionResult(functionFragment: 'abortKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getKalamangInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlockKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateWhitelist', data: BytesLike): Result;
  }

  

  export interface IKalamangStorage extends BaseContract {
    
    connect(runner?: ContractRunner | null): IKalamangStorage;
    waitForDeployment(): Promise<this>;

    interface: IKalamangStorageInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    abortKalamang: TypedContractMethod<
      [_kalamangId: string, _creator: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    addWhitelist: TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimToken: TypedContractMethod<
      [_kalamangId: string, _claimTokens: BigNumberish, _recipient: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    createKalamang: TypedContractMethod<
      [_config: IKalamangStorage.KalamangConfigStruct, ],
      [void],
      'nonpayable'
    >
    

    
    getKalamangInfo: TypedContractMethod<
      [_kalamangId: string, ],
      [IKalamangStorage.KalamangInfoStructOutput],
      'view'
    >
    

    
    removeWhitelist: TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unlockKalamang: TypedContractMethod<
      [_kalamangId: string, _creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateWhitelist: TypedContractMethod<
      [_kalamangId: string, _isRequireWhitelist: boolean, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'abortKalamang'): TypedContractMethod<
      [_kalamangId: string, _creator: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addWhitelist'): TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimToken'): TypedContractMethod<
      [_kalamangId: string, _claimTokens: BigNumberish, _recipient: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createKalamang'): TypedContractMethod<
      [_config: IKalamangStorage.KalamangConfigStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getKalamangInfo'): TypedContractMethod<
      [_kalamangId: string, ],
      [IKalamangStorage.KalamangInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'removeWhitelist'): TypedContractMethod<
      [_kalamangId: string, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unlockKalamang'): TypedContractMethod<
      [_kalamangId: string, _creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateWhitelist'): TypedContractMethod<
      [_kalamangId: string, _isRequireWhitelist: boolean, _whitelist: AddressLike[], _creator: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }