/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAdminProjectRouter } from './IAdminProjectRouter.js';
export type { IKAP165 } from './IKAP165.js';
export type { IKAP20 } from './IKAP20.js';
export type { IKAP20S } from './IKAP20S.js';
export type { IKAP721 } from './IKAP721.js';
export type { IKAP721Enumerable } from './IKAP721Enumerable.js';
export type { IKAP721Metadata } from './IKAP721Metadata.js';
export type { IKAP721Receiver } from './IKAP721Receiver.js';
export type { IKYCBitkubChain } from './IKYCBitkubChain.js';
export type { IKalamangFeeStorage } from './IKalamangFeeStorage.js';
export type { IKalamangStorage } from './IKalamangStorage.js';
export type { ISdkTransferRouter } from './ISdkTransferRouter.js';