/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ISdkTransferRouterInterface extends Interface {
    getFunction(nameOrSignature: "transferKAP1155" | "transferKAP20(address,address,address,uint256,address)" | "transferKAP20(address,address,uint256,address)" | "transferKAP721"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalKAP20" | "ApprovalNFT" | "KTokenAddrAdded" | "KTokenAddrRemoved" | "TransferKAP1155" | "TransferKAP20" | "TransferKAP721"): EventFragment;

    encodeFunctionData(functionFragment: 'transferKAP1155', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferKAP20(address,address,address,uint256,address)', values: [AddressLike, AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferKAP20(address,address,uint256,address)', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferKAP721', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'transferKAP1155', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferKAP20(address,address,address,uint256,address)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferKAP20(address,address,uint256,address)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferKAP721', data: BytesLike): Result;
  }

  
    export namespace ApprovalKAP20Event {
      export type InputTuple = [tokenAddr: AddressLike, owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [tokenAddr: string, owner: string, spender: string, value: bigint];
      export interface OutputObject {tokenAddr: string, owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalNFTEvent {
      export type InputTuple = [tokenAddr: AddressLike, owner: AddressLike, spender: AddressLike, approved: boolean];
      export type OutputTuple = [tokenAddr: string, owner: string, spender: string, approved: boolean];
      export interface OutputObject {tokenAddr: string, owner: string, spender: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace KTokenAddrAddedEvent {
      export type InputTuple = [kTokenAddr: AddressLike];
      export type OutputTuple = [kTokenAddr: string];
      export interface OutputObject {kTokenAddr: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace KTokenAddrRemovedEvent {
      export type InputTuple = [kTokenAddr: AddressLike];
      export type OutputTuple = [kTokenAddr: string];
      export interface OutputObject {kTokenAddr: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferKAP1155Event {
      export type InputTuple = [tokenAddr: AddressLike, sender: AddressLike, recipient: AddressLike, id: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [tokenAddr: string, sender: string, recipient: string, id: bigint, amount: bigint];
      export interface OutputObject {tokenAddr: string, sender: string, recipient: string, id: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferKAP20Event {
      export type InputTuple = [tokenAddr: AddressLike, sender: AddressLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tokenAddr: string, sender: string, recipient: string, amount: bigint];
      export interface OutputObject {tokenAddr: string, sender: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferKAP721Event {
      export type InputTuple = [tokenAddr: AddressLike, sender: AddressLike, recipient: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [tokenAddr: string, sender: string, recipient: string, tokenId: bigint];
      export interface OutputObject {tokenAddr: string, sender: string, recipient: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ISdkTransferRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): ISdkTransferRouter;
    waitForDeployment(): Promise<this>;

    interface: ISdkTransferRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    transferKAP1155: TypedContractMethod<
      [_tokenAddr: AddressLike, _recipient: AddressLike, _id: BigNumberish, _amount: BigNumberish, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    "transferKAP20(address,address,address,uint256,address)": TypedContractMethod<
      [_callerAddr: AddressLike, _tokenAddr: AddressLike, _recipient: AddressLike, _amount: BigNumberish, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    "transferKAP20(address,address,uint256,address)": TypedContractMethod<
      [_tokenAddr: AddressLike, _recipient: AddressLike, _amount: BigNumberish, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferKAP721: TypedContractMethod<
      [_tokenAddr: AddressLike, _recipient: AddressLike, _tokenId: BigNumberish, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'transferKAP1155'): TypedContractMethod<
      [_tokenAddr: AddressLike, _recipient: AddressLike, _id: BigNumberish, _amount: BigNumberish, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferKAP20(address,address,address,uint256,address)'): TypedContractMethod<
      [_callerAddr: AddressLike, _tokenAddr: AddressLike, _recipient: AddressLike, _amount: BigNumberish, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferKAP20(address,address,uint256,address)'): TypedContractMethod<
      [_tokenAddr: AddressLike, _recipient: AddressLike, _amount: BigNumberish, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferKAP721'): TypedContractMethod<
      [_tokenAddr: AddressLike, _recipient: AddressLike, _tokenId: BigNumberish, _bitkubNext: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ApprovalKAP20'): TypedContractEvent<ApprovalKAP20Event.InputTuple, ApprovalKAP20Event.OutputTuple, ApprovalKAP20Event.OutputObject>;
getEvent(key: 'ApprovalNFT'): TypedContractEvent<ApprovalNFTEvent.InputTuple, ApprovalNFTEvent.OutputTuple, ApprovalNFTEvent.OutputObject>;
getEvent(key: 'KTokenAddrAdded'): TypedContractEvent<KTokenAddrAddedEvent.InputTuple, KTokenAddrAddedEvent.OutputTuple, KTokenAddrAddedEvent.OutputObject>;
getEvent(key: 'KTokenAddrRemoved'): TypedContractEvent<KTokenAddrRemovedEvent.InputTuple, KTokenAddrRemovedEvent.OutputTuple, KTokenAddrRemovedEvent.OutputObject>;
getEvent(key: 'TransferKAP1155'): TypedContractEvent<TransferKAP1155Event.InputTuple, TransferKAP1155Event.OutputTuple, TransferKAP1155Event.OutputObject>;
getEvent(key: 'TransferKAP20'): TypedContractEvent<TransferKAP20Event.InputTuple, TransferKAP20Event.OutputTuple, TransferKAP20Event.OutputObject>;
getEvent(key: 'TransferKAP721'): TypedContractEvent<TransferKAP721Event.InputTuple, TransferKAP721Event.OutputTuple, TransferKAP721Event.OutputObject>;

    filters: {
      
      'ApprovalKAP20(address,address,address,uint256)': TypedContractEvent<ApprovalKAP20Event.InputTuple, ApprovalKAP20Event.OutputTuple, ApprovalKAP20Event.OutputObject>;
      ApprovalKAP20: TypedContractEvent<ApprovalKAP20Event.InputTuple, ApprovalKAP20Event.OutputTuple, ApprovalKAP20Event.OutputObject>;
    

      'ApprovalNFT(address,address,address,bool)': TypedContractEvent<ApprovalNFTEvent.InputTuple, ApprovalNFTEvent.OutputTuple, ApprovalNFTEvent.OutputObject>;
      ApprovalNFT: TypedContractEvent<ApprovalNFTEvent.InputTuple, ApprovalNFTEvent.OutputTuple, ApprovalNFTEvent.OutputObject>;
    

      'KTokenAddrAdded(address)': TypedContractEvent<KTokenAddrAddedEvent.InputTuple, KTokenAddrAddedEvent.OutputTuple, KTokenAddrAddedEvent.OutputObject>;
      KTokenAddrAdded: TypedContractEvent<KTokenAddrAddedEvent.InputTuple, KTokenAddrAddedEvent.OutputTuple, KTokenAddrAddedEvent.OutputObject>;
    

      'KTokenAddrRemoved(address)': TypedContractEvent<KTokenAddrRemovedEvent.InputTuple, KTokenAddrRemovedEvent.OutputTuple, KTokenAddrRemovedEvent.OutputObject>;
      KTokenAddrRemoved: TypedContractEvent<KTokenAddrRemovedEvent.InputTuple, KTokenAddrRemovedEvent.OutputTuple, KTokenAddrRemovedEvent.OutputObject>;
    

      'TransferKAP1155(address,address,address,uint256,uint256)': TypedContractEvent<TransferKAP1155Event.InputTuple, TransferKAP1155Event.OutputTuple, TransferKAP1155Event.OutputObject>;
      TransferKAP1155: TypedContractEvent<TransferKAP1155Event.InputTuple, TransferKAP1155Event.OutputTuple, TransferKAP1155Event.OutputObject>;
    

      'TransferKAP20(address,address,address,uint256)': TypedContractEvent<TransferKAP20Event.InputTuple, TransferKAP20Event.OutputTuple, TransferKAP20Event.OutputObject>;
      TransferKAP20: TypedContractEvent<TransferKAP20Event.InputTuple, TransferKAP20Event.OutputTuple, TransferKAP20Event.OutputObject>;
    

      'TransferKAP721(address,address,address,uint256)': TypedContractEvent<TransferKAP721Event.InputTuple, TransferKAP721Event.OutputTuple, TransferKAP721Event.OutputObject>;
      TransferKAP721: TypedContractEvent<TransferKAP721Event.InputTuple, TransferKAP721Event.OutputTuple, TransferKAP721Event.OutputObject>;
    
    };
  }