/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KalamangWashingInterface extends Interface {
    getFunction(nameOrSignature: "acceptedKycLevel" | "activateOnlyKycAddress" | "adminRouter" | "adminTransfer" | "approve" | "balanceOf" | "baseKapURI" | "baseURI" | "burn" | "committee" | "exists" | "externalTransfer" | "getApproved" | "internalTransfer" | "isActivatedOnlyKycAddress" | "isApprovedForAll" | "kalamangStorageAddress" | "kapURI" | "kyc" | "mintKalamang" | "mintWithMetadata" | "name" | "ownerOf" | "pause" | "paused" | "project" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setAcceptedKycLevel" | "setAdmin" | "setApprovalForAll" | "setBaseURI" | "setCommittee" | "setKYC" | "setProject" | "setTokenURI" | "setTransferRouter" | "supportsInterface" | "symbol" | "tokenByIndex" | "tokenOfOwnerAll" | "tokenOfOwnerByIndex" | "tokenOfOwnerByPage" | "tokenURI" | "totalSupply" | "transferFrom" | "transferRouter" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "MintWithMetadata" | "Paused" | "SetAdmin" | "SetCommittee" | "Transfer" | "Unpaused" | "Uri"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptedKycLevel', values?: undefined): string;
encodeFunctionData(functionFragment: 'activateOnlyKycAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'adminRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'adminTransfer', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'baseKapURI', values?: undefined): string;
encodeFunctionData(functionFragment: 'baseURI', values?: undefined): string;
encodeFunctionData(functionFragment: 'burn', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'committee', values?: undefined): string;
encodeFunctionData(functionFragment: 'exists', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'externalTransfer', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'internalTransfer', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isActivatedOnlyKycAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'kalamangStorageAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'kapURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'kyc', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintKalamang', values: [AddressLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintWithMetadata', values: [AddressLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'project', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setAcceptedKycLevel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setBaseURI', values: [string]): string;
encodeFunctionData(functionFragment: 'setCommittee', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setKYC', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setProject', values: [string]): string;
encodeFunctionData(functionFragment: 'setTokenURI', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'setTransferRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenByIndex', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenOfOwnerAll', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tokenOfOwnerByIndex', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenOfOwnerByPage', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'acceptedKycLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activateOnlyKycAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseKapURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'committee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'externalTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'internalTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActivatedOnlyKycAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kalamangStorageAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kapURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintKalamang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintWithMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'project', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAcceptedKycLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBaseURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCommittee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setKYC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTransferRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenByIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenOfOwnerAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenOfOwnerByIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenOfOwnerByPage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintWithMetadataEvent {
      export type InputTuple = [operator: AddressLike, _tokenURI: string, _tokenId: BigNumberish];
      export type OutputTuple = [operator: string, _tokenURI: string, _tokenId: bigint];
      export interface OutputObject {operator: string, _tokenURI: string, _tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetAdminEvent {
      export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike, caller: AddressLike];
      export type OutputTuple = [oldAdmin: string, newAdmin: string, caller: string];
      export interface OutputObject {oldAdmin: string, newAdmin: string, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetCommitteeEvent {
      export type InputTuple = [oldCommittee: AddressLike, newCommittee: AddressLike, caller: AddressLike];
      export type OutputTuple = [oldCommittee: string, newCommittee: string, caller: string];
      export interface OutputObject {oldCommittee: string, newCommittee: string, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UriEvent {
      export type InputTuple = [id: BigNumberish];
      export type OutputTuple = [id: bigint];
      export interface OutputObject {id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KalamangWashing extends BaseContract {
    
    connect(runner?: ContractRunner | null): KalamangWashing;
    waitForDeployment(): Promise<this>;

    interface: KalamangWashingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptedKycLevel: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activateOnlyKycAddress: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    adminRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    adminTransfer: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    baseKapURI: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    baseURI: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    burn: TypedContractMethod<
      [_from: AddressLike, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    committee: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    exists: TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    externalTransfer: TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, tokenId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    internalTransfer: TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, tokenId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    isActivatedOnlyKycAddress: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    kalamangStorageAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    kapURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    kyc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    mintKalamang: TypedContractMethod<
      [_to: AddressLike, _tokenURI: string, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mintWithMetadata: TypedContractMethod<
      [_to: AddressLike, _tokenURI: string, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    project: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, _data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setAcceptedKycLevel: TypedContractMethod<
      [_kycLevel: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setAdmin: TypedContractMethod<
      [_adminRouter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setBaseURI: TypedContractMethod<
      [_baseURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    setCommittee: TypedContractMethod<
      [_committee: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setKYC: TypedContractMethod<
      [_kyc: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setProject: TypedContractMethod<
      [_project: string, ],
      [void],
      'nonpayable'
    >
    

    
    setTokenURI: TypedContractMethod<
      [_tokenId: BigNumberish, _tokenURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    setTransferRouter: TypedContractMethod<
      [_transferRouter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenByIndex: TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    tokenOfOwnerAll: TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    tokenOfOwnerByIndex: TypedContractMethod<
      [owner: AddressLike, index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    tokenOfOwnerByPage: TypedContractMethod<
      [_owner: AddressLike, _page: BigNumberish, _limit: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptedKycLevel'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activateOnlyKycAddress'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'adminTransfer'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'baseKapURI'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'baseURI'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [_from: AddressLike, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'committee'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'exists'): TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'externalTransfer'): TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, tokenId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'internalTransfer'): TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, tokenId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isActivatedOnlyKycAddress'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'kalamangStorageAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'kapURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'kyc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mintKalamang'): TypedContractMethod<
      [_to: AddressLike, _tokenURI: string, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintWithMetadata'): TypedContractMethod<
      [_to: AddressLike, _tokenURI: string, _tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'project'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, _data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAcceptedKycLevel'): TypedContractMethod<
      [_kycLevel: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAdmin'): TypedContractMethod<
      [_adminRouter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBaseURI'): TypedContractMethod<
      [_baseURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCommittee'): TypedContractMethod<
      [_committee: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setKYC'): TypedContractMethod<
      [_kyc: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProject'): TypedContractMethod<
      [_project: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenURI'): TypedContractMethod<
      [_tokenId: BigNumberish, _tokenURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTransferRouter'): TypedContractMethod<
      [_transferRouter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenByIndex'): TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenOfOwnerAll'): TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'tokenOfOwnerByIndex'): TypedContractMethod<
      [owner: AddressLike, index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenOfOwnerByPage'): TypedContractMethod<
      [_owner: AddressLike, _page: BigNumberish, _limit: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'MintWithMetadata'): TypedContractEvent<MintWithMetadataEvent.InputTuple, MintWithMetadataEvent.OutputTuple, MintWithMetadataEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'SetAdmin'): TypedContractEvent<SetAdminEvent.InputTuple, SetAdminEvent.OutputTuple, SetAdminEvent.OutputObject>;
getEvent(key: 'SetCommittee'): TypedContractEvent<SetCommitteeEvent.InputTuple, SetCommitteeEvent.OutputTuple, SetCommitteeEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Uri'): TypedContractEvent<UriEvent.InputTuple, UriEvent.OutputTuple, UriEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'MintWithMetadata(address,string,uint256)': TypedContractEvent<MintWithMetadataEvent.InputTuple, MintWithMetadataEvent.OutputTuple, MintWithMetadataEvent.OutputObject>;
      MintWithMetadata: TypedContractEvent<MintWithMetadataEvent.InputTuple, MintWithMetadataEvent.OutputTuple, MintWithMetadataEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'SetAdmin(address,address,address)': TypedContractEvent<SetAdminEvent.InputTuple, SetAdminEvent.OutputTuple, SetAdminEvent.OutputObject>;
      SetAdmin: TypedContractEvent<SetAdminEvent.InputTuple, SetAdminEvent.OutputTuple, SetAdminEvent.OutputObject>;
    

      'SetCommittee(address,address,address)': TypedContractEvent<SetCommitteeEvent.InputTuple, SetCommitteeEvent.OutputTuple, SetCommitteeEvent.OutputObject>;
      SetCommittee: TypedContractEvent<SetCommitteeEvent.InputTuple, SetCommitteeEvent.OutputTuple, SetCommitteeEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Uri(uint256)': TypedContractEvent<UriEvent.InputTuple, UriEvent.OutputTuple, UriEvent.OutputObject>;
      Uri: TypedContractEvent<UriEvent.InputTuple, UriEvent.OutputTuple, UriEvent.OutputObject>;
    
    };
  }